GET http://localhost:5000/
###

POST http://localhost:5000/user/create HTTP/1.1
content-type: application/x-www-form-urlencoded

first_name=Airatk&last_name=Shram&email=Mufasa@gmail.com&password=LionKing
###

POST http://localhost:5000/user/delete HTTP/1.1
content-type: application/x-www-form-urlencoded

key=Mufasa-1561707574075958858
###

POST http://localhost:5000/user/edit HTTP/1.1
content-type: application/x-www-form-urlencoded

key=Mufasa-5504840107973441344&first_name=Airatka&last_name=Hram&password=LionKing2
###

# Mufasa@gmail.com     | LionKing | Mufasa-7060439016582037422
GET http://localhost:5000/user/Mufasa-7060439016582037422/view HTTP/1.1
###

POST http://localhost:5000/user/view HTTP/1.1
content-type: application/x-www-form-urlencoded

email=Mufasa@gmail.com&password=LionKing
###



POST http://localhost:5000/transaction/Mufasa-5498381435679789444/create HTTP/1.1
content-type: application/x-www-form-urlencoded

amount=-5
###

POST http://localhost:5000/transaction/delete HTTP/1.1
content-type: application/x-www-form-urlencoded
###

POST http://localhost:5000/transaction/Mufasa-5498381435679789444/edit/6 HTTP/1.1
content-type: application/x-www-form-urlencoded

amount=-50000
###

GET http://localhost:5000/transaction/Mufasa-5498381435679789444/view/4 HTTP/1.1
###

GET http://localhost:5000/transaction/Mufasa-5498381435679789444/view_all/2021.06.06 HTTP/1.1
###

GET http://localhost:5000/transaction/Mufasa-5498381435679789444/grouped HTTP/1.1
